version: '3.8'

services:
  backend:
    build: .
    container_name: backend-app
    ports:
      - "3800:3800"
    environment:
      - MONGODB_URI=${MONGODB_URI}  
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev